version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bello_horizonte_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bello
      POSTGRES_PASSWORD: bello2024
      POSTGRES_DB: bello_horizonte
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
